include classpath("application.conf")

queues {
  "upload-confirmation" {}
  "notification" {}
  "withdrawal" {}
  "periodic-command" {}
  "parrot-sound-detection" {}
  "parrot-sound-detection-dlq" {}
  "judgment-result" {}
}
