"""add push deliveries and notification i18n

Revision ID: 7521ade614c1
Revises: 545b840f3e07
Create Date: 2026-10-05 16:08:21.410393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7521ade614c1'
down_revision: Union[str, Sequence[str], None] = '545b840f3e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=True),
    sa.Column('announcement_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('push_deliveries_announcement_id_fkey')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('push_deliveries_device_id_fkey')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('push_deliveries_notification_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('push_deliveries_pkey'))
    )
    op.create_index('ix_push_deliveries_scheduled_at', 'push_deliveries', ['scheduled_at'], unique=False, postgresql_where=sa.text('queued_at IS NULL'))
    op.add_column('announcements', sa.Column('push_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('announcements', sa.Column('push_local_time', sa.Time(), nullable=True))
    op.add_column('announcements', sa.Column('push_prepared_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('locale', sa.Text(), server_default='en-US', nullable=False))
    op.add_column('notifications', sa.Column('title_i18n_id', sa.UUID(), nullable=False))
    op.add_column('notifications', sa.Column('body_i18n_id', sa.UUID(), nullable=False))
    op.add_column('notifications', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_notifications_session_id', 'notifications', ['session_id'])
    op.drop_constraint(op.f('notifications_sound_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_session_id_fkey'), 'notifications', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(op.f('notifications_body_i18n_id_fkey'), 'notifications', 'i18n', ['body_i18n_id'], ['id'])
    op.create_foreign_key(op.f('notifications_title_i18n_id_fkey'), 'notifications', 'i18n', ['title_i18n_id'], ['id'])
    op.drop_column('notifications', 'body')
    op.drop_column('notifications', 'report_date')
    op.drop_column('notifications', 'sound_id')
    op.drop_column('notifications', 'title')
    op.add_column('user_settings', sa.Column('push_notification_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user_settings', sa.Column('marketing_night_notification_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'marketing_night_notification_enabled')
    op.drop_column('user_settings', 'push_notification_enabled')
    op.add_column('notifications', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('sound_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('notifications_title_i18n_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_body_i18n_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_session_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_sound_id_fkey'), 'notifications', 'session_sounds', ['sound_id'], ['id'])
    op.drop_constraint('uq_notifications_session_id', 'notifications', type_='unique')
    op.drop_column('notifications', 'session_id')
    op.drop_column('notifications', 'body_i18n_id')
    op.drop_column('notifications', 'title_i18n_id')
    op.drop_column('devices', 'locale')
    op.drop_column('announcements', 'push_prepared_at')
    op.drop_column('announcements', 'push_local_time')
    op.drop_column('announcements', 'push_enabled')
    op.drop_index('ix_push_deliveries_scheduled_at', table_name='push_deliveries', postgresql_where=sa.text('queued_at IS NULL'))
    op.drop_table('push_deliveries')
    # ### end Alembic commands ###
