"""move device role to session

Revision ID: 256d51df0dc4
Revises: a9f60f388783
Create Date: 2026-09-21 13:15:42.049419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256d51df0dc4'
down_revision: Union[str, Sequence[str], None] = 'a9f60f388783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_devices_station_active'), table_name='devices', postgresql_where="((role = 'station'::text) AND (is_deleted = false))")
    op.drop_index(op.f('uq_devices_viewer_active'), table_name='devices', postgresql_where="((role = 'viewer'::text) AND (is_deleted = false))")
    op.drop_column('devices', 'role')
    op.drop_column('session_events', 'occurred_by')
    op.drop_index(op.f('uq_sessions_station_running'), table_name='sessions', postgresql_where="((status = 'running'::text) AND (is_deleted = false))")
    op.create_index('uq_sessions_user_running', 'sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'running' AND is_deleted = false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sessions_user_running', table_name='sessions', postgresql_where=sa.text("status = 'running' AND is_deleted = false"))
    op.create_index(op.f('uq_sessions_station_running'), 'sessions', ['station_device_id'], unique=True, postgresql_where="((status = 'running'::text) AND (is_deleted = false))")
    op.add_column('session_events', sa.Column('occurred_by', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index(op.f('uq_devices_viewer_active'), 'devices', ['user_id'], unique=True, postgresql_where="((role = 'viewer'::text) AND (is_deleted = false))")
    op.create_index(op.f('uq_devices_station_active'), 'devices', ['user_id'], unique=True, postgresql_where="((role = 'station'::text) AND (is_deleted = false))")
    # ### end Alembic commands ###
