"""add word recording display order

Revision ID: d8df85d1e726
Revises: de3469e7e7ab
Create Date: 2026-10-04 00:37:01.904521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8df85d1e726'
down_revision: Union[str, Sequence[str], None] = 'de3469e7e7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_recordings', sa.Column('display_order', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_recordings', 'display_order')
    # ### end Alembic commands ###
