"""add user identities and session ended reason

Revision ID: a3229298a4fd
Revises: cf3be82589fa
Create Date: 2026-10-08 08:43:15.858566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3229298a4fd'
down_revision: Union[str, Sequence[str], None] = 'cf3be82589fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_identities_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'provider', name=op.f('user_identities_pkey'))
    )
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_index(op.f('ix_parrots_user_id'), 'parrots', ['user_id'], unique=False)
    op.add_column('sessions', sa.Column('ended_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'ended_reason')
    op.drop_index(op.f('ix_parrots_user_id'), table_name='parrots')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_table('user_identities')
    # ### end Alembic commands ###
