"""change unique constraint for label_categories table

Revision ID: 765cb00187e5
Revises: 8d2dfa5863db
Create Date: 2026-08-28 22:35:50.118718

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '765cb00187e5'
down_revision: str | Sequence[str] | None = '8d2dfa5863db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('label_categories_name_key'), 'label_categories', type_='unique')
    op.create_unique_constraint(None, 'label_categories', ['name', 'target'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'label_categories', type_='unique')
    op.create_unique_constraint(op.f('label_categories_name_key'), 'label_categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
