"""add audio_captures table

Revision ID: 6a3acbb853c4
Revises: 0ec869332f47
Create Date: 2026-08-04 11:19:02.993468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3acbb853c4'
down_revision: Union[str, Sequence[str], None] = '0ec869332f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_captures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_anon_uid', sa.Text(), nullable=False),
    sa.Column('client_capture_id', sa.Text(), nullable=False),
    sa.Column('client_session_id', sa.Text(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=True),
    sa.Column('client_word_id', sa.Text(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('parrot_species', sa.String(length=50), nullable=True),
    sa.Column('parrot_birthdate', sa.Date(), nullable=True),
    sa.Column('app_version', sa.Text(), nullable=True),
    sa.Column('device_platform', sa.Text(), nullable=True),
    sa.Column('device_os_version', sa.Text(), nullable=True),
    sa.Column('device_model', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_passed', sa.Boolean(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('word_entries', 'client_word_id',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word_entries', 'client_word_id',
               existing_type=sa.TEXT(),
               server_default=sa.text("'preset-annyeoung'::text"),
               existing_nullable=False)
    op.drop_table('audio_captures')
    # ### end Alembic commands ###
