"""store one app update per version

Revision ID: 4d902a2b8287
Revises: f4ff362b3c92
Create Date: 2026-10-08 20:56:30.270077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d902a2b8287'
down_revision: Union[str, Sequence[str], None] = 'f4ff362b3c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    invalid_versions = op.get_bind().scalars(
        sa.text(
            """
            SELECT latest_version
            FROM app_updates
            WHERE latest_version !~ :pattern
            UNION ALL
            SELECT min_supported_version
            FROM (
                SELECT DISTINCT ON (platform) min_supported_version
                FROM app_updates
                ORDER BY platform, created_at DESC, id DESC
            ) AS latest
            WHERE min_supported_version !~ :pattern
            """
        ),
        {"pattern": r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$"},
    ).all()

    if invalid_versions:
        raise ValueError(f"app_updates has versions that are not three dot-separated numbers: {invalid_versions}")

    op.add_column('app_updates', sa.Column('version', sa.String(length=12), nullable=True))
    op.add_column('app_updates', sa.Column('is_forced', sa.Boolean(), nullable=True))
    op.execute("UPDATE app_updates SET version = latest_version, is_forced = false")
    op.execute(
        """
        DELETE FROM app_updates AS a
        USING app_updates AS b
        WHERE a.platform = b.platform
            AND a.version = b.version
            AND (a.created_at, a.id) < (b.created_at, b.id)
        """
    )
    op.create_unique_constraint('uq_app_updates_platform_version', 'app_updates', ['platform', 'version'])
    op.execute(
        """
        INSERT INTO app_updates (id, platform, version, is_forced, latest_version, min_supported_version)
        SELECT DISTINCT ON (platform)
            gen_random_uuid(), platform, min_supported_version, true, latest_version, min_supported_version
        FROM app_updates
        ORDER BY platform, created_at DESC, id DESC
        ON CONFLICT (platform, version) DO UPDATE SET is_forced = true
        """
    )
    op.alter_column('app_updates', 'version', nullable=False)
    op.alter_column('app_updates', 'is_forced', nullable=False)
    op.drop_column('app_updates', 'min_supported_version')
    op.drop_column('app_updates', 'latest_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_updates', sa.Column('latest_version', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.add_column('app_updates', sa.Column('min_supported_version', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.drop_constraint('uq_app_updates_platform_version', 'app_updates', type_='unique')
    op.drop_column('app_updates', 'is_forced')
    op.drop_column('app_updates', 'version')
    # ### end Alembic commands ###
