"""add app updates

Revision ID: e1a623b87b20
Revises: 7e0bb148b38d
Create Date: 2026-10-01 09:20:55.530276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a623b87b20'
down_revision: Union[str, Sequence[str], None] = '7e0bb148b38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('latest_version', sa.String(length=12), nullable=False),
    sa.Column('min_supported_version', sa.String(length=12), nullable=False),
    sa.Column('release_notes_i18n_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['release_notes_i18n_id'], ['i18n.id'], name=op.f('app_updates_release_notes_i18n_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_updates_pkey')),
    sa.UniqueConstraint('platform', name='uq_app_updates_platform')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_updates')
    # ### end Alembic commands ###
