"""add marketing notification setting

Revision ID: de3469e7e7ab
Revises: 0bc1a50eadfb
Create Date: 2026-10-04 00:34:02.120157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3469e7e7ab'
down_revision: Union[str, Sequence[str], None] = '0bc1a50eadfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('marketing_notification_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'marketing_notification_enabled')
    # ### end Alembic commands ###
