"""add dashboard indexes

Revision ID: cf3be82589fa
Revises: add0e36b65ff
Create Date: 2026-10-07 19:13:36.090669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3be82589fa'
down_revision: Union[str, Sequence[str], None] = 'add0e36b65ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_session_events_occurred_at_emergency_detected', 'session_events', ['occurred_at'], unique=False, postgresql_where=sa.text("kind = 'emergency_detected'"))
    op.create_index('ix_session_sounds_updated_at_failed', 'session_sounds', ['updated_at'], unique=False, postgresql_where=sa.text("judgment_status = 'failed'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_sounds_updated_at_failed', table_name='session_sounds', postgresql_where=sa.text("judgment_status = 'failed'"))
    op.drop_index('ix_session_events_occurred_at_emergency_detected', table_name='session_events', postgresql_where=sa.text("kind = 'emergency_detected'"))
    # ### end Alembic commands ###
