"""move notice and consent texts to i18n

Revision ID: 7e0bb148b38d
Revises: 1319a0d288cc
Create Date: 2026-09-30 22:51:59.765610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0bb148b38d'
down_revision: Union[str, Sequence[str], None] = '1319a0d288cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i18n',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ko_kr', sa.Text(), nullable=True),
    sa.Column('en_us', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('i18n_pkey'))
    )
    op.add_column('consents', sa.Column('title_i18n_id', sa.UUID(), nullable=False))
    op.add_column('consents', sa.Column('body_i18n_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('consents_body_i18n_id_fkey'), 'consents', 'i18n', ['body_i18n_id'], ['id'])
    op.create_foreign_key(op.f('consents_title_i18n_id_fkey'), 'consents', 'i18n', ['title_i18n_id'], ['id'])
    op.drop_column('consents', 'body')
    op.drop_column('consents', 'title')
    op.add_column('notices', sa.Column('title_i18n_id', sa.UUID(), nullable=False))
    op.add_column('notices', sa.Column('body_i18n_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('notices_body_i18n_id_fkey'), 'notices', 'i18n', ['body_i18n_id'], ['id'])
    op.create_foreign_key(op.f('notices_title_i18n_id_fkey'), 'notices', 'i18n', ['title_i18n_id'], ['id'])
    op.drop_column('notices', 'body')
    op.drop_column('notices', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('notices', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('notices_title_i18n_id_fkey'), 'notices', type_='foreignkey')
    op.drop_constraint(op.f('notices_body_i18n_id_fkey'), 'notices', type_='foreignkey')
    op.drop_column('notices', 'body_i18n_id')
    op.drop_column('notices', 'title_i18n_id')
    op.add_column('consents', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('consents', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('consents_title_i18n_id_fkey'), 'consents', type_='foreignkey')
    op.drop_constraint(op.f('consents_body_i18n_id_fkey'), 'consents', type_='foreignkey')
    op.drop_column('consents', 'body_i18n_id')
    op.drop_column('consents', 'title_i18n_id')
    op.drop_table('i18n')
    # ### end Alembic commands ###
