"""add push delivery sent at

Revision ID: 68a183f75d7c
Revises: 7521ade614c1
Create Date: 2026-10-05 18:11:07.613390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a183f75d7c'
down_revision: Union[str, Sequence[str], None] = '7521ade614c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_deliveries', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_deliveries', 'sent_at')
    # ### end Alembic commands ###
