"""make preset word names unique among active rows

Revision ID: f1cdec7f8237
Revises: d8df85d1e726
Create Date: 2026-10-04 17:26:08.699594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cdec7f8237'
down_revision: Union[str, Sequence[str], None] = 'd8df85d1e726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_preset_words_language_name'), 'preset_words', type_='unique')
    op.create_index('uq_preset_words_language_name_active', 'preset_words', ['language', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_preset_words_language_name_active', table_name='preset_words', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_preset_words_language_name'), 'preset_words', ['language', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
