"""add session schedule and drop session settings

Revision ID: 36f1a1380bf9
Revises: 8d3ace390251
Create Date: 2026-09-30 22:16:32.850232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f1a1380bf9'
down_revision: Union[str, Sequence[str], None] = '8d3ace390251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('sleep_at', sa.Time(), nullable=True))
    op.add_column('sessions', sa.Column('wake_at', sa.Time(), nullable=True))
    op.alter_column('sessions', 'word_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('sessions', 'applied_settings_version')
    op.drop_column('sessions', 'learning_enabled')
    op.drop_column('sessions', 'settings_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('settings_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('learning_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('applied_settings_version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('sessions', 'word_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('sessions', 'wake_at')
    op.drop_column('sessions', 'sleep_at')
    op.drop_column('sessions', 'scheduled_end_at')
    # ### end Alembic commands ###
