"""remove unique constraint in label_categories table and label_options table

Revision ID: 68295984c508
Revises: 765cb00187e5
Create Date: 2026-08-28 22:44:30.826043

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68295984c508'
down_revision: str | Sequence[str] | None = '765cb00187e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('label_categories_name_target_key'), 'label_categories', type_='unique')
    op.drop_constraint(op.f('label_options_category_id_name_key'), 'label_options', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('label_options_category_id_name_key'), 'label_options', ['category_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('label_categories_name_target_key'), 'label_categories', ['name', 'target'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
