"""add sound analyses and session event sounds

Revision ID: add0e36b65ff
Revises: 68a183f75d7c
Create Date: 2026-10-06 20:27:52.443215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add0e36b65ff'
down_revision: Union[str, Sequence[str], None] = '68a183f75d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_event_sounds',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sound_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['session_events.id'], name=op.f('session_event_sounds_event_id_fkey')),
    sa.ForeignKeyConstraint(['sound_id'], ['session_sounds.id'], name=op.f('session_event_sounds_sound_id_fkey')),
    sa.PrimaryKeyConstraint('event_id', 'sound_id', name=op.f('session_event_sounds_pkey'))
    )
    op.create_table('sound_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sound_id', sa.UUID(), nullable=False),
    sa.Column('analyzer_version', sa.Text(), nullable=False),
    sa.Column('is_parrot', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('chirp_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['sound_id'], ['session_sounds.id'], name=op.f('sound_analyses_sound_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sound_analyses_pkey')),
    sa.UniqueConstraint('sound_id', 'analyzer_version', name='uq_sound_analyses_sound_id_analyzer_version')
    )
    op.add_column('session_sounds', sa.Column('judgment_status', sa.Text(), server_default='pending', nullable=False))
    op.execute("UPDATE session_sounds SET judgment_status = CASE WHEN is_parrot_sound IS NULL THEN 'failed' ELSE 'done' END")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_sounds', 'judgment_status')
    op.drop_table('sound_analyses')
    op.drop_table('session_event_sounds')
    # ### end Alembic commands ###
