"""add session notification and push delivery indexes

Revision ID: e1de12fbbdbc
Revises: a3229298a4fd
Create Date: 2026-10-08 10:21:31.162668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1de12fbbdbc'
down_revision: Union[str, Sequence[str], None] = 'a3229298a4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notifications_sent_at', 'notifications', ['sent_at'], unique=False)
    op.create_index('ix_push_deliveries_device_id_sent_at', 'push_deliveries', ['device_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_sessions_ended_at'), 'sessions', ['ended_at'], unique=False)
    op.create_index(op.f('ix_sessions_started_at'), 'sessions', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_started_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_ended_at'), table_name='sessions')
    op.drop_index('ix_push_deliveries_device_id_sent_at', table_name='push_deliveries')
    op.drop_index('ix_notifications_sent_at', table_name='notifications')
    # ### end Alembic commands ###
