"""big change

Revision ID: cf6067f31499
Revises: 68295984c508
Create Date: 2026-09-01 13:33:20.368496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf6067f31499'
down_revision: Union[str, Sequence[str], None] = '68295984c508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_captures', sa.Column('memo', sa.Text(), nullable=True))
    op.alter_column('audio_captures', 'app_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=12),
               existing_nullable=True)
    op.alter_column('audio_captures', 'device_platform',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('audio_captures', 'device_os_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('audio_captures', 'device_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('audio_captures', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('audio_captures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audio_captures', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audio_captures', 'version_id',
               existing_type=sa.BIGINT(),
               server_default='0',
               existing_nullable=False)
    op.create_index(op.f('ix_audio_captures_audio_file_id'), 'audio_captures', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_audio_captures_word_id'), 'audio_captures', ['word_id'], unique=False)
    op.alter_column('audio_segments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('audio_segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audio_segments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audio_segments', 'version_id',
               existing_type=sa.BIGINT(),
               server_default='0',
               existing_nullable=False)
    op.create_index(op.f('ix_audio_segments_audio_file_id'), 'audio_segments', ['audio_file_id'], unique=False)
    op.alter_column('files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('files', 'version_id',
               existing_type=sa.BIGINT(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('label_categories', 'display_order',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('label_categories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('label_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('label_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('label_categories', 'version_id',
               existing_type=sa.BIGINT(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('label_options', 'display_order',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('label_options', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('label_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('label_options', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('label_options', 'version_id',
               existing_type=sa.BIGINT(),
               server_default='0',
               existing_nullable=False)
    op.create_index(op.f('ix_label_options_category_id'), 'label_options', ['category_id'], unique=False)
    op.alter_column('word_entries', 'is_preset',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('word_entries', 'device_platform',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('word_entries', 'device_os_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('word_entries', 'device_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('word_entries', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('word_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('word_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('word_entries', 'version_id',
               existing_type=sa.BIGINT(),
               server_default='0',
               existing_nullable=False)
    op.create_index(op.f('ix_word_entries_audio_file_id'), 'word_entries', ['audio_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_entries_audio_file_id'), table_name='word_entries')
    op.alter_column('word_entries', 'version_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('word_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('word_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('word_entries', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('word_entries', 'device_model',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('word_entries', 'device_os_version',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('word_entries', 'device_platform',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('word_entries', 'is_preset',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_label_options_category_id'), table_name='label_options')
    op.alter_column('label_options', 'version_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('label_options', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('label_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('label_options', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('label_options', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('label_categories', 'version_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('label_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('label_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('label_categories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('label_categories', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'version_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_audio_segments_audio_file_id'), table_name='audio_segments')
    op.alter_column('audio_segments', 'version_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audio_segments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audio_segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audio_segments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_audio_captures_word_id'), table_name='audio_captures')
    op.drop_index(op.f('ix_audio_captures_audio_file_id'), table_name='audio_captures')
    op.alter_column('audio_captures', 'version_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audio_captures', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audio_captures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audio_captures', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audio_captures', 'device_model',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audio_captures', 'device_os_version',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audio_captures', 'device_platform',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audio_captures', 'app_version',
               existing_type=sa.String(length=12),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('audio_captures', 'memo')
    # ### end Alembic commands ###
