"""add notify_mimicry

Revision ID: 8fea94ca14da
Revises: 41b96aee3151
Create Date: 2026-09-18 15:54:04.778374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fea94ca14da'
down_revision: Union[str, Sequence[str], None] = '41b96aee3151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('notify_mimicry', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'notify_mimicry')
    # ### end Alembic commands ###
