"""init database

Revision ID: c84f6c6023d1
Revises: 
Create Date: 2026-08-04 13:18:17.293712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84f6c6023d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_file_name'), 'files', ['file_name'], unique=False)
    op.create_table('word_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('firebase_anon_uid', sa.Text(), nullable=True),
    sa.Column('client_word_id', sa.Text(), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('device_platform', sa.Text(), nullable=True),
    sa.Column('device_os_version', sa.Text(), nullable=True),
    sa.Column('device_model', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_captures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_anon_uid', sa.Text(), nullable=False),
    sa.Column('client_capture_id', sa.Text(), nullable=False),
    sa.Column('client_session_id', sa.Text(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=True),
    sa.Column('client_word_id', sa.Text(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('parrot_species', sa.String(length=50), nullable=True),
    sa.Column('parrot_birthdate', sa.Date(), nullable=True),
    sa.Column('app_version', sa.Text(), nullable=True),
    sa.Column('device_platform', sa.Text(), nullable=True),
    sa.Column('device_os_version', sa.Text(), nullable=True),
    sa.Column('device_model', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_passed', sa.Boolean(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_captures')
    op.drop_table('word_entries')
    op.drop_index(op.f('ix_files_file_name'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
