"""add push delivery notification index

Revision ID: 6e6d6c509088
Revises: 4d902a2b8287
Create Date: 2026-10-08 22:38:21.428602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6d6c509088'
down_revision: Union[str, Sequence[str], None] = '4d902a2b8287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_push_deliveries_notification_id'), 'push_deliveries', ['notification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_deliveries_notification_id'), table_name='push_deliveries')
    # ### end Alembic commands ###
