"""add user anonymous flag

Revision ID: 0bc1a50eadfb
Revises: e1a623b87b20
Create Date: 2026-10-01 09:25:57.656529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc1a50eadfb'
down_revision: Union[str, Sequence[str], None] = 'e1a623b87b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_anonymous')
    # ### end Alembic commands ###
