"""alter firebase_anon_uid limit to 30 in word_entries table

Revision ID: 6756160370ab
Revises: a3f5c7d91e24
Create Date: 2026-09-01 10:35:31.481617

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6756160370ab'
down_revision: str | Sequence[str] | None = 'a3f5c7d91e24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_captures', sa.Column('memo', sa.Text(), nullable=True))
    op.alter_column('word_entries', 'firebase_anon_uid',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word_entries', 'firebase_anon_uid',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('audio_captures', 'memo')
    # ### end Alembic commands ###
