"""allow multiple app updates per platform

Revision ID: 6d823bd65acf
Revises: e1de12fbbdbc
Create Date: 2026-10-08 16:24:20.034319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d823bd65acf'
down_revision: Union[str, Sequence[str], None] = 'e1de12fbbdbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_app_updates_platform'), 'app_updates', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_app_updates_platform'), 'app_updates', ['platform'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
