"""replace learning daily summary with learning segments

Revision ID: e144d64b754a
Revises: 36f1a1380bf9
Create Date: 2026-09-30 22:21:14.719072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e144d64b754a'
down_revision: Union[str, Sequence[str], None] = '36f1a1380bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('play_duration_ms', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('learning_segments_session_id_fkey')),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('learning_segments_word_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_segments_pkey')),
    sa.UniqueConstraint('session_id', 'word_id', 'started_at', name='uq_learning_segments_session_id_word_id_started_at')
    )
    op.create_index('ix_learning_segments_word_id_started_at', 'learning_segments', ['word_id', 'started_at'], unique=False)
    op.drop_index(op.f('ix_learning_daily_summary_word_id_local_date'), table_name='learning_daily_summary')
    op.drop_table('learning_daily_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_daily_summary',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('word_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('local_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('play_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('play_duration_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('learning_daily_summary_session_id_fkey')),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('learning_daily_summary_word_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_daily_summary_pkey')),
    sa.UniqueConstraint('session_id', 'word_id', 'local_date', name=op.f('uq_learning_daily_summary_session_id_word_id_local_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_learning_daily_summary_word_id_local_date'), 'learning_daily_summary', ['word_id', 'local_date'], unique=False)
    op.drop_index('ix_learning_segments_word_id_started_at', table_name='learning_segments')
    op.drop_table('learning_segments')
    # ### end Alembic commands ###
