"""add absence session tables

Revision ID: e3041621b15f
Revises: 4176d7f03f86
Create Date: 2026-09-17 21:36:40.667509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3041621b15f'
down_revision: Union[str, Sequence[str], None] = '4176d7f03f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preset_words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'name', name='uq_preset_words_language_name')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_device_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('os_version', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('app_version', sa.String(length=12), nullable=False),
    sa.Column('push_token', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.CheckConstraint("role IN ('station', 'viewer')", name='ck_devices_role'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_device_id', name='uq_devices_user_id_client_device_id')
    )
    op.create_index('uq_devices_station_active', 'devices', ['user_id'], unique=True, postgresql_where=sa.text("role = 'station' AND is_deleted = false"))
    op.create_index('uq_devices_viewer_active', 'devices', ['user_id'], unique=True, postgresql_where=sa.text("role = 'viewer' AND is_deleted = false"))
    op.create_table('parrots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('photo_file_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['photo_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_file_id', name='uq_parrots_photo_file_id')
    )
    op.create_table('processed_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('response_status', sa.SmallInteger(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'request_id', name='uq_processed_requests_user_id_request_id')
    )
    op.create_table('user_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('notice_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'notice_version', name='uq_user_consents_user_id_kind_notice_version')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sleep_at', sa.Time(), server_default='20:00', nullable=False),
    sa.Column('wake_at', sa.Time(), server_default='08:00', nullable=False),
    sa.Column('notify_emergency', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_daily_summary', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_streak', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_station_disconnect', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_user_id'), 'words', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('station_device_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=True),
    sa.Column('learning_enabled', sa.Boolean(), nullable=False),
    sa.Column('settings_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('applied_settings_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_phase', sa.Text(), nullable=True),
    sa.Column('phase_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_by', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.CheckConstraint("status IN ('running', 'finished')", name='ck_sessions_status'),
    sa.ForeignKeyConstraint(['station_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_last_heartbeat_at_running', 'sessions', ['last_heartbeat_at'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index('uq_sessions_station_running', 'sessions', ['station_device_id'], unique=True, postgresql_where=sa.text("status = 'running' AND is_deleted = false"))
    op.create_table('word_recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_recordings_word_id'), 'word_recordings', ['word_id'], unique=False)
    op.create_table('learning_daily_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('play_duration_ms', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'word_id', 'local_date', name='uq_learning_daily_summary_session_id_word_id_local_date')
    )
    op.create_index('ix_learning_daily_summary_word_id_local_date', 'learning_daily_summary', ['word_id', 'local_date'], unique=False)
    op.create_table('session_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_by', sa.Text(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=True),
    sa.Column('emergency_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_events_session_id_occurred_at', 'session_events', ['session_id', 'occurred_at'], unique=False)
    op.create_table('session_sounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('is_parrot_sound', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_sounds_session_id_captured_at', 'session_sounds', ['session_id', 'captured_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('emergency_event_id', sa.UUID(), nullable=True),
    sa.Column('image_file_id', sa.UUID(), nullable=True),
    sa.Column('sound_id', sa.UUID(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['image_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['sound_id'], ['session_sounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id_sent_at', 'notifications', ['user_id', 'sent_at'], unique=False)
    op.create_table('sound_judgments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sound_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['sound_id'], ['session_sounds.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sound_judgments_sound_id_judged_at', 'sound_judgments', ['sound_id', 'judged_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sound_judgments_sound_id_judged_at', table_name='sound_judgments')
    op.drop_table('sound_judgments')
    op.drop_index('ix_notifications_user_id_sent_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_session_sounds_session_id_captured_at', table_name='session_sounds')
    op.drop_table('session_sounds')
    op.drop_index('ix_session_events_session_id_occurred_at', table_name='session_events')
    op.drop_table('session_events')
    op.drop_index('ix_learning_daily_summary_word_id_local_date', table_name='learning_daily_summary')
    op.drop_table('learning_daily_summary')
    op.drop_index(op.f('ix_word_recordings_word_id'), table_name='word_recordings')
    op.drop_table('word_recordings')
    op.drop_index('uq_sessions_station_running', table_name='sessions', postgresql_where=sa.text("status = 'running' AND is_deleted = false"))
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_last_heartbeat_at_running', table_name='sessions', postgresql_where=sa.text("status = 'running'"))
    op.drop_table('sessions')
    op.drop_index(op.f('ix_words_user_id'), table_name='words')
    op.drop_table('words')
    op.drop_table('user_settings')
    op.drop_table('user_consents')
    op.drop_table('processed_requests')
    op.drop_table('parrots')
    op.drop_index('uq_devices_viewer_active', table_name='devices', postgresql_where=sa.text("role = 'viewer' AND is_deleted = false"))
    op.drop_index('uq_devices_station_active', table_name='devices', postgresql_where=sa.text("role = 'station' AND is_deleted = false"))
    op.drop_table('devices')
    op.drop_table('preset_words')
    # ### end Alembic commands ###
