"""add client_word_id in word table

Revision ID: 0ec869332f47
Revises: 7afe3115b624
Create Date: 2026-08-03 23:29:09.552570

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ec869332f47"
down_revision: str | Sequence[str] | None = "7afe3115b624"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "word_entries", sa.Column("client_word_id", sa.Text(), nullable=False, server_default="preset-annyeoung")
    )
    op.alter_column("word_entries", "firebase_anon_uid", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("word_entries", "firebase_anon_uid", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("word_entries", "client_word_id")
    # ### end Alembic commands ###
