"""replace notification settings and drop emergency event id

Revision ID: 1319a0d288cc
Revises: dc6bd7476bd9
Create Date: 2026-09-30 22:36:44.582434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1319a0d288cc'
down_revision: Union[str, Sequence[str], None] = 'dc6bd7476bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'emergency_event_id')
    op.add_column('user_settings', sa.Column('notice_notification_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user_settings', sa.Column('report_notification_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_column('user_settings', 'notify_emergency')
    op.drop_column('user_settings', 'notify_streak')
    op.drop_column('user_settings', 'notify_station_disconnect')
    op.drop_column('user_settings', 'notify_daily_summary')
    op.drop_column('user_settings', 'notify_mimicry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('notify_mimicry', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('user_settings', sa.Column('notify_daily_summary', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('user_settings', sa.Column('notify_station_disconnect', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('user_settings', sa.Column('notify_streak', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('user_settings', sa.Column('notify_emergency', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('user_settings', 'report_notification_enabled')
    op.drop_column('user_settings', 'notice_notification_enabled')
    op.add_column('notifications', sa.Column('emergency_event_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
