"""add user withdrawal failures

Revision ID: 1257d2dfaabc
Revises: 6d823bd65acf
Create Date: 2026-10-08 17:40:56.894472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1257d2dfaabc'
down_revision: Union[str, Sequence[str], None] = '6d823bd65acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_withdrawal_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_withdrawal_failures_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_withdrawal_failures_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_withdrawal_failures')
    # ### end Alembic commands ###
