"""add notification dispatches

Revision ID: f4ff362b3c92
Revises: 1257d2dfaabc
Create Date: 2026-10-08 18:50:41.733552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ff362b3c92'
down_revision: Union[str, Sequence[str], None] = '1257d2dfaabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_dispatches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title_i18n_id', sa.UUID(), nullable=False),
    sa.Column('body_i18n_id', sa.UUID(), nullable=False),
    sa.Column('image_file_id', sa.UUID(), nullable=True),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('recipient_local_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['body_i18n_id'], ['i18n.id'], name=op.f('notification_dispatches_body_i18n_id_fkey')),
    sa.ForeignKeyConstraint(['image_file_id'], ['files.id'], name=op.f('notification_dispatches_image_file_id_fkey')),
    sa.ForeignKeyConstraint(['title_i18n_id'], ['i18n.id'], name=op.f('notification_dispatches_title_i18n_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_dispatches_pkey'))
    )
    op.add_column('notifications', sa.Column('dispatch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_notifications_dispatch_id'), 'notifications', ['dispatch_id'], unique=False)
    op.create_foreign_key(op.f('notifications_dispatch_id_fkey'), 'notifications', 'notification_dispatches', ['dispatch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_dispatch_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_dispatch_id'), table_name='notifications')
    op.drop_column('notifications', 'dispatch_id')
    op.drop_table('notification_dispatches')
    # ### end Alembic commands ###
