"""add label, audio_segments table for backoffice

Revision ID: dadf384c0c41
Revises: c84f6c6023d1
Create Date: 2026-08-19 18:29:15.095003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dadf384c0c41'
down_revision: Union[str, Sequence[str], None] = 'c84f6c6023d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('label_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['label_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name')
    )
    op.create_table('audio_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audio_capture_id', sa.UUID(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('label_option_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['audio_capture_id'], ['audio_captures.id'], ),
    sa.ForeignKeyConstraint(['audio_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['label_option_id'], ['label_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_segments_audio_capture_id'), 'audio_segments', ['audio_capture_id'], unique=False)
    op.create_index(op.f('ix_audio_segments_label_option_id'), 'audio_segments', ['label_option_id'], unique=False)
    op.drop_column('audio_captures', 'review_note')
    op.drop_column('audio_captures', 'reviewed_at')
    op.drop_column('audio_captures', 'review_passed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_captures', sa.Column('review_passed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('audio_captures', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('audio_captures', sa.Column('review_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audio_segments_label_option_id'), table_name='audio_segments')
    op.drop_index(op.f('ix_audio_segments_audio_capture_id'), table_name='audio_segments')
    op.drop_table('audio_segments')
    op.drop_table('label_options')
    op.drop_table('label_categories')
    # ### end Alembic commands ###
