"""allow backoffice processed requests

Revision ID: 409b3f302db7
Revises: 6e6d6c509088
Create Date: 2026-10-09 13:32:45.327600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409b3f302db7'
down_revision: Union[str, Sequence[str], None] = '6e6d6c509088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processed_requests', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_processed_requests_user_id_request_id'), 'processed_requests', type_='unique')
    op.create_unique_constraint('uq_processed_requests_user_id_request_id', 'processed_requests', ['user_id', 'request_id'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM processed_requests WHERE user_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_processed_requests_user_id_request_id', 'processed_requests', type_='unique')
    op.create_unique_constraint(op.f('uq_processed_requests_user_id_request_id'), 'processed_requests', ['user_id', 'request_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('processed_requests', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
