"""add memo column to audio_segments

Revision ID: 4ef782785c99
Revises: dadf384c0c41
Create Date: 2026-08-24 12:32:01.361236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef782785c99'
down_revision: Union[str, Sequence[str], None] = 'dadf384c0c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_segments', sa.Column('memo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_segments', 'memo')
    # ### end Alembic commands ###
