"""allow add label to audio_captures

Revision ID: 8d2dfa5863db
Revises: 4ef782785c99
Create Date: 2026-08-28 22:02:32.640568

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d2dfa5863db'
down_revision: str | Sequence[str] | None = '4ef782785c99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_capture_labels',
    sa.Column('audio_capture_id', sa.UUID(), nullable=False),
    sa.Column('label_option_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audio_capture_id'], ['audio_captures.id'], ),
    sa.ForeignKeyConstraint(['label_option_id'], ['label_options.id'], ),
    sa.PrimaryKeyConstraint('audio_capture_id', 'label_option_id')
    )
    op.create_index(op.f('ix_audio_capture_labels_label_option_id'), 'audio_capture_labels', ['label_option_id'], unique=False)
    op.add_column('label_categories', sa.Column('target', sa.Text(), server_default=sa.text("'SE'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label_categories', 'target')
    op.drop_index(op.f('ix_audio_capture_labels_label_option_id'), table_name='audio_capture_labels')
    op.drop_table('audio_capture_labels')
    # ### end Alembic commands ###
