"""add feedback, notice and consent tables

Revision ID: 41b96aee3151
Revises: e3041621b15f
Create Date: 2026-09-18 13:23:19.545399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b96aee3151'
down_revision: Union[str, Sequence[str], None] = 'e3041621b15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('consents_pkey')),
    sa.UniqueConstraint('kind', 'version', name='uq_consents_kind_version')
    )
    op.create_index('ix_consents_kind_published_at', 'consents', ['kind', 'published_at'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name='ck_notices_period'),
    sa.PrimaryKeyConstraint('id', name=op.f('notices_pkey'))
    )
    op.create_index('ix_notices_starts_at', 'notices', ['starts_at'], unique=False)
    op.create_table('notice_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('notice_images_file_id_fkey')),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], name=op.f('notice_images_notice_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notice_images_pkey')),
    sa.UniqueConstraint('file_id', name='uq_notice_images_file_id'),
    sa.UniqueConstraint('notice_id', 'display_order', name='uq_notice_images_notice_id_display_order')
    )
    op.create_table('notice_reads',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], name=op.f('notice_reads_notice_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notice_reads_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'notice_id', name=op.f('notice_reads_pkey'))
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('app_version', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('feedbacks_device_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('feedbacks_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedbacks_pkey'))
    )
    op.create_index('ix_feedbacks_created_at', 'feedbacks', ['created_at'], unique=False)
    op.add_column('user_consents', sa.Column('consent_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_user_consents_user_id_kind_notice_version'), 'user_consents', type_='unique')
    op.create_unique_constraint('uq_user_consents_user_id_consent_id', 'user_consents', ['user_id', 'consent_id'])
    op.create_foreign_key(op.f('user_consents_consent_id_fkey'), 'user_consents', 'consents', ['consent_id'], ['id'])
    op.drop_column('user_consents', 'kind')
    op.drop_column('user_consents', 'notice_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_consents', sa.Column('notice_version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_consents', sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('user_consents_consent_id_fkey'), 'user_consents', type_='foreignkey')
    op.drop_constraint('uq_user_consents_user_id_consent_id', 'user_consents', type_='unique')
    op.create_unique_constraint(op.f('uq_user_consents_user_id_kind_notice_version'), 'user_consents', ['user_id', 'kind', 'notice_version'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_consents', 'consent_id')
    op.drop_index('ix_feedbacks_created_at', table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_table('notice_reads')
    op.drop_table('notice_images')
    op.drop_index('ix_notices_starts_at', table_name='notices')
    op.drop_table('notices')
    op.drop_index('ix_consents_kind_published_at', table_name='consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
