"""add uploading photo files

Revision ID: dc6bd7476bd9
Revises: e144d64b754a
Create Date: 2026-09-30 22:32:41.969169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6bd7476bd9'
down_revision: Union[str, Sequence[str], None] = 'e144d64b754a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parrots', sa.Column('uploading_photo_file_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_parrots_uploading_photo_file_id', 'parrots', ['uploading_photo_file_id'])
    op.create_foreign_key(op.f('parrots_uploading_photo_file_id_fkey'), 'parrots', 'files', ['uploading_photo_file_id'], ['id'])
    op.add_column('users', sa.Column('uploading_photo_file_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_users_uploading_photo_file_id', 'users', ['uploading_photo_file_id'])
    op.create_foreign_key(op.f('users_uploading_photo_file_id_fkey'), 'users', 'files', ['uploading_photo_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_uploading_photo_file_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint('uq_users_uploading_photo_file_id', 'users', type_='unique')
    op.drop_column('users', 'uploading_photo_file_id')
    op.drop_constraint(op.f('parrots_uploading_photo_file_id_fkey'), 'parrots', type_='foreignkey')
    op.drop_constraint('uq_parrots_uploading_photo_file_id', 'parrots', type_='unique')
    op.drop_column('parrots', 'uploading_photo_file_id')
    # ### end Alembic commands ###
