"""add user withdrawals

Revision ID: 4176d7f03f86
Revises: 07c1cf479fff
Create Date: 2026-09-16 15:28:42.488708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4176d7f03f86'
down_revision: Union[str, Sequence[str], None] = '07c1cf479fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('credentials_ciphertext', sa.Text(), nullable=False),
    sa.Column('proof_digest', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.CheckConstraint("provider IN ('google', 'apple')", name='ck_user_oauth_credentials_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'identity_id', 'client_id')
    )
    op.create_table('user_withdrawals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_status', sa.Text(), nullable=False),
    sa.Column('apple_status', sa.Text(), nullable=False),
    sa.Column('kakao_status', sa.Text(), nullable=False),
    sa.Column('kakao_user_ids_ciphertext', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.CheckConstraint("apple_status IN ('not_required', 'pending', 'completed', 'unconfirmed')", name='ck_user_withdrawals_apple_status'),
    sa.CheckConstraint("google_status IN ('not_required', 'pending', 'completed', 'unconfirmed')", name='ck_user_withdrawals_google_status'),
    sa.CheckConstraint("kakao_status IN ('not_required', 'pending', 'completed')", name='ck_user_withdrawals_kakao_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_user_withdrawals_attempt_count'),
    sa.CheckConstraint('completed_at IS NULL OR next_attempt_at IS NULL', name='ck_user_withdrawals_completed_schedule'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_user_withdrawals_next_attempt_at', 'user_withdrawals', ['next_attempt_at'], unique=False, postgresql_where=sa.text('completed_at IS NULL AND next_attempt_at IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_withdrawals_next_attempt_at', table_name='user_withdrawals', postgresql_where=sa.text('completed_at IS NULL AND next_attempt_at IS NOT NULL'))
    op.drop_table('user_withdrawals')
    op.drop_table('user_oauth_credentials')
    # ### end Alembic commands ###
